# prettier-ignore
name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - 
        name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      -
        name: Get PNPM store directory
        id: pnpm-cache
        shell: bash 
        run: | 
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - 
        name: Cache
        uses: actions/cache@v3
        with: 
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - 
        name: Install Dependencies
        run: pnpm install
      - 
        name: Test
        run: pnpm test
      - 
        name: Build
        run: pnpm build
